public class application {
    public static void main(String[] args) {
        char isfirstyear = 'T';
        char isTransferee ='T';
        char isReturnee = 'T';
        String LastName = "Polu";
        String FirstName = "Teja";
        String MiddleName = "sri";
        String CompleteAddress = "Ganguru ,Vijayawada";
        String DateOfBirth =  "12/sep/2002";
        String birthplace = "Nellore";
        boolean Citizenship = true;
        boolean isfemale = true;
        String CivilStatus = "Single";
        long contactnumber = 1023495253;
        String Name_of_Spouse = "N/A";
        String Father_Name = "Ramana Reddy";
        String Occupation = "Worker";
        int FatherContact = 1987534534;
        String GuardianName = "N/A";
        String GuardianAddress = "N/A";
        String Mother_Name = "Kondamma";
        String occupation = "Worker";
        long MotherNumber = 23984395773l;
        String Senior_High_School = "Noble";
        short Year_Graduate = 2018;
        float Gen_Average = 9.0f;
        String Last_School_Attended = "April-2025";
        String Course = "B.Tech";
        short Last_School_Year = 2025;
        boolean isAlsPasser_yes = true;
        boolean isAlsPasser_no = false;
        int year_taken = 2005;
        boolean is4psbeneficiary_yes = true;
        boolean is4psbeneficiary_no = false;
        long fourpsID_NO = 23875948502l;
        boolean isDisable_yes = false;
        boolean isDisavle_no = true;
        String Type_of_disability ="N/A";
        System.out.println(isfirstyear);
        System.out.println(isTransferee);
        System.out.println(isReturnee);
        System.out.println(LastName);
        System.out.println(FirstName);
        System.out.println(MiddleName);
        System.out.println(CompleteAddress);
        System.out.println(DateOfBirth);
        System.out.println(birthplace);
        System.out.println(Citizenship);
        System.out.println(isfemale);
        System.out.println(CivilStatus);
        System.out.println(contactnumber);
        System.out.println(Name_of_Spouse);
        System.out.println(Father_Name );
        System.out.println(Occupation);
        System.out.println(FatherContact);
        System.out.println(GuardianName);
        System.out.println(GuardianAddress);
        System.out.println(Mother_Name);
        System.out.println(occupation);
        System.out.println(MotherNumber);
        System.out.println(Senior_High_School);
        System.out.println(Year_Graduate);
        System.out.println(Gen_Average);  
        System.out.println(Last_School_Attended);
        System.out.println(Course); 
        System.out.println(Last_School_Year);
        System.out.println(isAlsPasser_yes); 
        System.out.println(isAlsPasser_no); 
        System.out.println(year_taken);
        System.out.println(is4psbeneficiary_yes); 
        System.out.println(is4psbeneficiary_no); 
        System.out.println(fourpsID_NO);
        System.out.println(isDisable_yes); 
        System.out.println(isDisavle_no); 
         System.out.println(Type_of_disability); 
    }
}
